Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-12"
  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4048"
    vb.cpus = 2
  end
end

